let t = "ABRIR | to open
yo	abro	nosotros	abrimos
tú	abres	vosotros	abrís
él	abre	ellos	abren
ella	abre	ellas	abren
usted	abre	ustedes	abren
APRENDER | to learn
yo	aprendo	nosotros	aprendemos
tú	aprendes	vosotros	aprendéis
él	aprende	ellos	aprenden
ella	aprende	ellas	aprenden
usted	aprende	ustedes	aprenden
ASISTIR | to attend
yo	asisto	nosotros	asistimos
tú	asistes	vosotros	asistís
él	asiste	ellos	asisten
ella	asiste	ellas	asisten
usted	asiste	ustedes	asisten
BAILAR | to dance
yo	bailo	nosotros	bailamos
tú	bailas	vosotros	bailáis
él	baila	ellos	bailan
ella	baila	ellas	bailan
usted	baila	ustedes	bailan
BARRER | to sweep (broom)
yo	barro	nosotros	barremos
tú	barres	vosotros	barréis
él	barre	ellos	barren
ella	barre	ellas	barren
usted	barre	ustedes	barren
BEBER | to drink
yo	bebo	nosotros	bebemos
tú	bebes	vosotros	bebéis
él	bebe	ellos	beben
ella	bebe	ellas	beben
usted	bebe	ustedes	beben
BORRAR | to erase
yo	borro	nosotros	borramos
tú	borras	vosotros	borráis
él	borra	ellos	borran
ella	borra	ellas	borran
usted	borra	ustedes	borran
CAMINAR | to walk
yo	camino	nosotros	caminamos
tú	caminas	vosotros	camináis
él	camina	ellos	caminan
ella	camina	ellas	caminan
usted	camina	ustedes	caminan
CANTAR | to sing
yo	canto	nosotros	cantamos
tú	cantas	vosotros	cantáis
él	canta	ellos	cantan
ella	canta	ellas	cantan
usted	canta	ustedes	cantan
COCINAR | to cook
yo	cocino	nosotros	cocinamos
tú	cocinas	vosotros	cocináis
él	cocina	ellos	cocinan
ella	cocina	ellas	cocinan
usted	cocina	ustedes	cocinan
COMER | to eat
yo	como	nosotros	comemos
tú	comes	vosotros	coméis
él	come	ellos	comen
ella	come	ellas	comen
usted	come	ustedes	comen
COMPRENDER | to understand
yo	comprendo	nosotros	comprendemos
tú	comprendes	vosotros	comprendéis
él	comprende	ellos	comprenden
ella	comprende	ellas	comprenden
usted	comprende	ustedes	comprenden
CORRER | to run
yo	corro	nosotros	corremos
tú	corres	vosotros	corréis
él	corre	ellos	corren
ella	corre	ellas	corren
usted	corre	ustedes	corren
DIBUJAR | to draw
yo	dibujo	nosotros	dibujamos
tú	dibujas	vosotros	dibujáis
él	dibuja	ellos	dibujan
ella	dibuja	ellas	dibujan
usted	dibuja	ustedes	dibujan
ESCRIBIR | to write
yo	escribo	nosotros	escribimos
tú	escribes	vosotros	escribís
él	escribe	ellos	escriben
ella	escribe	ellas	escriben
usted	escribe	ustedes	escriben
ESCUCHAR | to listen (to)
yo	escucho	nosotros	escuchamos
tú	escuchas	vosotros	escucháis
él	escucha	ellos	escuchan
ella	escucha	ellas	escuchan
usted	escucha	ustedes	escuchan
HABLAR | to talk
yo	hablo	nosotros	hablamos
tú	hablas	vosotros	habláis
él	habla	ellos	hablan
ella	habla	ellas	hablan
usted	habla	ustedes	hablan
LAVAR | to wash
yo	lavo	nosotros	lavamos
tú	lavas	vosotros	laváis
él	lava	ellos	lavan
ella	lava	ellas	lavan
usted	lava	ustedes	lavan
LEER | to read
yo	leo	nosotros	leemos
tú	lees	vosotros	leéis
él	lee	ellos	leen
ella	lee	ellas	leen
usted	lee	ustedes	leen
LIMPIAR | to clean
yo	limpio	nosotros	limpiamos
tú	limpias	vosotros	limpiáis
él	limpia	ellos	limpian
ella	limpia	ellas	limpian
usted	limpia	ustedes	limpian
LLEVAR | to wear/to bring
yo	llevo	nosotros	llevamos
tú	llevas	vosotros	lleváis
él	lleva	ellos	llevan
ella	lleva	ellas	llevan
usted	lleva	ustedes	llevan
MIRAR | to look
yo	miro	nosotros	miramos
tú	miras	vosotros	miráis
él	mira	ellos	miran
ella	mira	ellas	miran
usted	mira	ustedes	miran
MONTAR | to get on
yo	monto	nosotros	montamos
tú	montas	vosotros	montáis
él	monta	ellos	montan
ella	monta	ellas	montan
usted	monta	ustedes	montan
NADAR | to swim
yo	nado	nosotros	nadamos
tú	nadas	vosotros	nadáis
él	nada	ellos	nadan
ella	nada	ellas	nadan
usted	nada	ustedes	nadan
PRESTAR | to lend
yo	presto	nosotros	prestamos
tú	prestas	vosotros	prestáis
él	presta	ellos	prestan
ella	presta	ellas	prestan
usted	presta	ustedes	prestan
RECIBIR | to receive
yo	recibo	nosotros	recibimos
tú	recibes	vosotros	recibís
él	recibe	ellos	reciben
ella	recibe	ellas	reciben
usted	recibe	ustedes	reciben
SUBIR | to go up/to rise
yo	subo	nosotros	subimos
tú	subes	vosotros	subís
él	sube	ellos	suben
ella	sube	ellas	suben
usted	sube	ustedes	suben
VENDER | to sell
yo	vendo	nosotros	vendemos
tú	vendes	vosotros	vendéis
él	vende	ellos	venden
ella	vende	ellas	venden
usted	vende	ustedes	venden
VIVIR | to live
yo	vivo	nosotros	vivimos
tú	vives	vosotros	vivís
él	vive	ellos	viven
ella	vive	ellas	viven
usted	vive	ustedes	viven";
